api/urls.py
from django.urls import path

from api.views import BookReviewDetailApiView
app_name = "api"

urlpatterns = [
    path("reviews/<int:id>/", BookReviewDetailApiView.as_view(), name="review-detail"),

]

books/urls.py
from django.urls import path
from .views import BooksView, BookDetailView, BookCreateView, AddReviewView

app_name = 'books'

urlpatterns = [
    path('', BooksView.as_view(), name='list'),
    path('<int:id>', BookDetailView.as_view(), name='detail'),
    path('create/', BookCreateView.as_view(), name="create"),
    path('<int:id>/reviews/', AddReviewView.as_view(), name='reviews')
]

goodreads/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import landing_page, home_page

urlpatterns = [
    path('books/', include('books.urls')),
    path('', landing_page, name='landing_page'),
    path('users/', include('users.urls')),
    path('api/', include('api.urls')),

    path('admin/', admin.site.urls),
    path('home/', home_page, name='home_page'),
    path('api-auth/', include('rest_framework.urls'))
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import RegisterView, LoginView, ProfileView, LogoutView, ProfileUpdateView
app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name="register"),
    path('login/', LoginView.as_view(), name="login"),
    path('profile/', ProfileView.as_view(), name="profile"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('profile/edit/', ProfileUpdateView.as_view(), name="profile-edit"),
]

templates/base.html
{% load static %}

{% url 'home_page' as home_page_url %}
{% url 'books:list' as book_page_url %}
{% url 'users:profile' as profile_page_url %}
{% url 'users:profile-edit' as profile_edit_page_url %}


{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Goodreads Kloni{% endblock title %}</title>

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css">

</head>
<body class="mx-5">



<nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-2">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url "landing_page" %}">GOODREADS</a>
    <button class="navbar-toggler bg-light"  type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link {% if request.path == home_page_url %} active {% endif %} " aria-current="page" href="{{ home_page_url }}">HOME</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == book_page_url %} active {% endif %} " aria-current="page" href="{{ book_page_url }}">BOOKS</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == profile_page_url %} active {% endif %} " aria-current="page" href="{{ profile_page_url }}">PROFILE</a>
        </li>

      </ul>

        {% if not request.user.is_authenticated %}

            <a class="btn btn-outline-info" href="{% url 'users:login' %}">Login</a>


            <a class="btn btn-outline-info" href="{% url 'users:register' %}">Register</a>

        {% else %}
           <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle {% if request.path == profile_page_url or request.path == profile_edit_page_url %} active {% endif %}" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {{ request.user.username.title }}
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{{ profile_page_url }}">Profile</a></li>
                  <li><a class="dropdown-item" href="{% url 'users:logout' %}"> Logout</a></li>

              </ul>
            </li>
            </ul>


        {% endif %}

    </div>
  </div>
</nav>



<div class="container">
    {% if messages %}
        <div class="mt-4">
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}" role="alert">
            {{ message }}
            </div>
        {% endfor %}
            </div>
    {% endif %}

    {% block content %}

    {% endblock content %}
</div>



<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}
    Home
{% endblock title %}

{% block content %}
    <br>
    <h3>All Reviews</h3>

    {% for review in page_obj %}
        <div class="container posts-content">
            <div class="row">

                <div class="col-lg-6">
                    <div class="card mb-4">
                      <div class="card-body">
                        <div class="media mb-3">
                          <img src="{{ review.user.profile_image.url }}" class="d-block ui-w-40 rounded-circle"  alt="">
                          <div class="media-body ml-3">
                            <b>{{ review.user.username }}</b> rated this book {{ review.stars_given }} stars
                            <div class="text-muted small">{{ review.created_at }}</div>
                          </div>
                        </div>

                        <p>
                          {{ review.comment | truncatechars:150 }}
                        </p>
                          <img class="cover-pic center" src="{{ review.book.cover_picture.url }}" alt="">

                      </div>

                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

    <nav aria-label="...">
      <ul class="pagination">
      {% if page_obj.has_previous %}
         <li class="page-item">
          <a class="page-link" href="{% url 'home_page' %}?page=1">&laquo; birinchi</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="{% url 'home_page' %}?page={{ page_obj.previous_page_number }}">oldingi</a>
        </li>

      {% endif %}
        <li class="page-item active" aria-current="page">

          <a class="page-link" href="#">{{ page_obj.number }}</a>
        </li>
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="{% url 'home_page' %}?page={{ page_obj.next_page_number }}">keyingi</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="{% url 'home_page' %}?page={{ page_obj.paginator.num_pages }}">oxirgi</a>
        </li>
      {% endif %}
      </ul>
    </nav>


{% endblock content %}

templates/landing.html
{% extends 'base.html' %}


{% block content %}

<h1>Landing Page</h1>


<p>Goodreads is an American social cataloging website and a subsidiary of Amazon[1] that allows individuals to search its database of books, annotations, quotes, and reviews. Users can sign up and register books to generate library catalogs and reading lists. They can also create their own groups of book suggestions, surveys, polls, blogs, and discussions. The website's offices are located in San Francisco.[2]

Goodreads was founded in December 2006 and launched in January 2007 by Otis Chandler and Elizabeth Khuri Chandler.[3][4] In December 2007, the site had 650,000 members[5] and 10,000,000 books had been added.[6] By July 2012, the site reported 10 million members, 20 million monthly visits, and thirty employees.[7] On March 28, 2013, Amazon announced its acquisition of Goodreads,[8] and by July 23, 2013, Goodreads announced their user base had grown to 20 million members.[9]

By July 2019, the site had 90 million members.[10]</p>
{% endblock content %}