api/urls.py
from django.urls import path

from api.views import BookReviewDetailApiView
app_name = "api"

urlpatterns = [
    path("reviews/<int:id>/", BookReviewDetailApiView.as_view(), name="review-detail"),

]

books/urls.py
from django.urls import path
from .views import BooksView, BookDetailView, BookCreateView, AddReviewView

app_name = 'books'

urlpatterns = [
    path('', BooksView.as_view(), name='list'),
    path('<int:id>', BookDetailView.as_view(), name='detail'),
    path('create/', BookCreateView.as_view(), name="create"),
    path('<int:id>/reviews/', AddReviewView.as_view(), name='reviews')
]

goodreads/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import landing_page, home_page

urlpatterns = [
    path('books/', include('books.urls')),
    path('', landing_page, name='landing_page'),
    path('users/', include('users.urls')),
    path('api/', include('api.urls')),

    path('admin/', admin.site.urls),
    path('home/', home_page, name='home_page'),
    path('api-auth/', include('rest_framework.urls'))
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.utils import timezone

from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from users.models import CustomUser


class Book(models.Model):
    title = models.CharField(max_length=200)  # Varchar
    description = models.TextField()
    isbn = models.CharField(max_length=17)
    cover_picture = models.ImageField(default="default_cover.jpg")

    def __str__(self):
        return self.title


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    bio = models.TextField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def full_name(self):
        return f"{self.first_name} {self.last_name}"


class BookAuthor(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.book.title} by {self.author.first_name} {self.author.last_name}"


class BookReview(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    comment = models.TextField()
    stars_given = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.stars_given} stars for {self.book.title}  by {self.user.username}"

books/forms.py
from django import forms

from .models import Book, BookReview


class BookCreateForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'description', 'isbn','cover_picture']


class BookReviewForm(forms.ModelForm):
    stars_given = forms.IntegerField(min_value=1, max_value=5 )

    class Meta:
        model = BookReview
        fields = ['comment', 'stars_given']

books/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View

from .models import Book, BookReview
from .forms import BookCreateForm, BookReviewForm


# class BooksView(ListView):
#     template_name = 'books/list.html'
#     queryset = Book.objects.all()
#     context_object_name = 'books'
#     paginate_by = 2


class BooksView(View):
    def get(self, request):
        books = Book.objects.all().order_by('id')
        search_query = request.GET.get('q', '')
        if search_query:
            books = books.distinct().filter(Q(title__icontains=search_query) |
                                            Q(description__icontains=search_query))

        page_size = request.GET.get('page_size', 2)
        paginator = Paginator(books, page_size)

        page_num = request.GET.get('page', 1)
        page_obj = paginator.get_page(page_num)
        context = {
            'page_obj': page_obj,
            'search_query': search_query
        }
        return render(request, 'books/list.html', context)


# class BookDetailView(DetailView):
#     template_name = 'books/detail.html'
#     pk_url_kwarg = "pk"
#     model = Book
#     context_object_name = 'book'
class BookDetailView(View):
    def get(self, request, id):
        review_form = BookReviewForm()
        book = Book.objects.get(id=id)
        context = {
            'book': book,
            'review_form': review_form,
        }
        return render(request, 'books/detail.html', context)


class AddReviewView(LoginRequiredMixin, View):
    def post(self, request, id):
        book = Book.objects.get(id=id)
        review_form = BookReviewForm(request.POST)
        if review_form.is_valid():
            BookReview.objects.create(
                user=request.user,
                book=book,
                stars_given=review_form.cleaned_data[
                    'stars_given'
                ],
                comment=review_form.cleaned_data['comment'],
            )
            return redirect(reverse('books:detail', kwargs={'id': book.id}))
        context = {
            'book': book,
            'review_form': review_form,
        }
        return render(request, 'books/detail.html', context)


class BookCreateView(View):
    #
    def get(self, request):
        form = BookCreateForm()

        context = {
            'form': form,
        }
        return render(request, 'books/create.html', context)

    def post(self, request):
        form = BookCreateForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.info(request, "Kitob muvaffaqiyatli qo'shildi")
            return redirect('books:list')
        context = {
            'form': form,
        }
        return render(request, 'books/create.html', context)

books/templates/books/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
<h3>Book Create Page</h3>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">saqlash</button>
    </form>
{% endblock %}

books/templates/books/detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Book Detail{% endblock %}

<body>
{% block content %}

    <br>
    <div class="row">
        <div class="col-2">
            <img class='default-book' style="height: 250px; width: 200px" src="{{ book.cover_picture.url }}" alt="Kitob rasmi">
        </div>
        <div class="col-6 ms-3">
            <h3>{{ book.title }}</h3>
            <span class="fst-italic">Authored by:
            {% for book_author in book.bookauthor_set.all %}
                {% if forloop.last %}

                    <b>{{ book_author.author.full_name }}</b>
                {% else %}
                    <b>{{ book_author.author.full_name }},</b>
                {% endif %}
            {% endfor %}
            </span>

            <p>{{ book.description }}</p>
        </div>
    </div>

    <div class="row mb-4">
        <p>Izoh qoldirish:</p>
        <div class="col-6">
            <form method="post" action="{% url 'books:reviews' book.id %}">
                {% csrf_token %}
                {{ review_form | crispy }}
                <button type="submit" class="btn btn-success">Izoh qo'shish</button>
            </form>
        </div>
    </div>
    {% if book.bookreview_set.exists %}
    <h4>Izohlar</h4>
    {% endif %}

    <hr>

    {% for review in book.bookreview_set.all %}
        <div class="row mb-3">
            <div class="col-1 me-2">
                <img style="width: 100px; height: 100px" src="{{ review.user.profile_image.url }}" alt="Profil rasmi">
            </div>
            <div class="col-7">
                <b>{{ review.user.username }}</b> rated it {{ review.stars_given }} stars <span class="fw-lighter">{{ review.created_at }}</span>
                <p class="mt-2 font-monospace">{{ review.comment }}</p>
            </div>
        </div>

    {% endfor %}
{% endblock content %}
</body>
</html>

books/templates/books/list.html
{% extends 'base.html' %}

{% block title %}Books{% endblock %}
<body>
{% block content %}
<h1>Books</h1>
<div class="row mb-3">
    <div class="col-4">

        <form method="get">
            <div class="input-group mb-3">
                <input type="text" class="form-control form-control-lg" placeholder="Qidirish..." name="q" value="{{ search_query }}">
                <button type="submit" class="input-group-text btn-success"><i class="bi bi-search me-2"></i>Qidirish</button>
            </div>
        </form>
    </div>
</div>


{% if page_obj %}
    {% for book in page_obj %}
        <div class="row mb-4">
            <div class="col-2">
                <br><br>
                <img class="default-book" src="{{ book.cover_picture.url }}" >
            </div>
            <div class="col-6 ms-4">
            <br><br>
                <h3><a href="{% url 'books:detail' book.id %}">{{ book.title }}</a> </h3>
                <p>
                    {{ book.description }}
                </p>

            </div>

        </div>
        
    {% endfor %}

    <nav aria-label="...">
      <ul class="pagination">
      {% if page_obj.has_previous %}
         <li class="page-item">
          <a class="page-link" href="{% url 'books:list' %}?page=1">&laquo; birinchi</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="{% url 'books:list' %}?page={{ page_obj.previous_page_number }}">oldingi</a>
        </li>

      {% endif %}
        <li class="page-item active" aria-current="page">

          <a class="page-link" href="#">{{ page_obj.number }}</a>
        </li>
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="{% url 'books:list' %}?page={{ page_obj.next_page_number }}">keyingi</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="{% url 'books:list' %}?page={{ page_obj.paginator.num_pages }}">oxirgi</a>
        </li>
      {% endif %}
      </ul>
    </nav>






{% else %}
No books found.
{% endif %}

{% endblock content %}
</body>